# vim:ft=ansible

---
- hosts: all
  sudo: yes
  tasks:
    - name: (rbenv) install
      git:
        repo: 'https://github.com/sstephenson/rbenv.git'
        dest: /usr/local/rbenv

    - name: (rbenv) install ruby-build
      git:
        repo: 'https://github.com/sstephenson/ruby-build.git'
        dest: /usr/local/rbenv/plugins/ruby-build

    - name: (rbenv) create directory
      file:
        path: "/usr/local/rbenv/{{ item }}"
        state: directory
      with_items:
        - shims
        - versions

    - name: (rbenv) export path
      shell: mkdir -p /etc/profile.d
             && echo 'export RBENV_ROOT=/usr/local/rbenv' > /etc/profile.d/rbenv.sh
             && echo 'export PATH=$RBENV_ROOT/bin:$PATH' >> /etc/profile.d/rbenv.sh
             && echo 'eval "$(rbenv init -)"' >> /etc/profile.d/rbenv.sh
             && bash /etc/profile.d/rbenv.sh

    - name: (rbenv) setup rbenv
      shell: bash -lc 'CONFIGURE_OPTS='--disable-install-rdoc' rbenv install 2.3.0'
             && bash -lc 'rbenv global 2.3.0'
             && bash -lc 'exec gem install bundler'
             && bash -lc 'rbenv rehash'

